### ISSUE TITLE
window aspect >> 2 时的OSC界面问题

### ISSUE THREAD

**Issue by linger040831** [hooke007/MPV_lazy#110]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/84896599/163087505-0e2dff68-b9f9-4c24-84f5-0dd8b179b013.png">
如图，在没有进入最大化或全屏界面时，导航栏不会缩放，我在mpv.conf里找不到相关设置，是本来就是这样设计，还是我设置问题？望回复。

**Comment by hooke007** [comment]
恰相反，这是按照比例缩放后的结果。这种视频的比例太极端了，导致按钮去匹配过长的横向被迫缩的很小
（我从来没想过会有这种应用场景，毕竟常规视频没这么罕见的比例）

**Comment by linger040831** [comment]
好的谢谢回复，就是无意中发现的问题:x，幸苦老哥了。
