### ISSUE TITLE
音画不同步

### ISSUE THREAD

**Issue by BlueDolphin9527** [hooke007/MPV_lazy#115]
不清除是哪里出了问题，使用mpv_lazy220403版本就会音画不同步，画面不固定倍速播放，音频正常。
使用原版MPV或者纯净模式就正常，我猜应该是脚本出了问题，可是不会排查，还麻烦你修复一下。

**Comment by hooke007** [comment]
https://hooke007.github.io/mpv-lazy/[04]_%E5%B8%B8%E8%A7%81FAQ%EF%BC%88%E8%B8%A9%E5%9D%91%E5%BD%95%EF%BC%89.html#q-%E9%9F%B3%E7%94%BB%E4%B8%8D%E5%90%8C%E6%AD%A5

A2

**Comment by sunbeams001** [comment]
个人是修改了A5，猜测可能是显示器刷新率较高所致

**Comment by hooke007** [comment]
无响应关闭
