### ISSUE TITLE
鼠标左击暂停同时不和full screen冲突

### ISSUE THREAD

**Issue by phyzhenli** [hooke007/MPV_lazy#129]
我将play/pause调至鼠标左击，但双击full screen的时候会调用两次play/pause。能否在full screen的时候不调用呢？

我google了一下找不到类似的脚本，请问大神能否patch一个脚本？

万分感谢！

**Comment by hooke007** [comment]
我认为这应该向mpv提出feature request

**Comment by hooke007** [comment]
https://github.com/hooke007/MPV_lazy/blob/acd480536e18e76eecfdcfce1ec15949575267f4/portable_config/script-opts/uosc.conf#L92-L93

此脚本选项部分支持此功能
