### ISSUE TITLE
[Bug] 由GPU 100%占用所引发的系统死机

### ISSUE THREAD

**Issue by jerryfangr** [hooke007/MPV_lazy#145]
## 环境

硬件：GTX 1060 Notebook + i5-8400
系统：Win10 21H1 2022.06更新
软件：[mpv-lazy-20220515](https://github.com/hooke007/MPV_lazy/releases/tag/20220515)
设置：加一份崩溃前的日志，已打包为[portable_config.zip](https://github.com/hooke007/MPV_lazy/files/8960430/portable_config.zip)，修改参考配置描述。

## 配置

MPV主要修改为如下
+ mpv.conf 33行，修改了GPU名称
+ mpv.conf 52行，修改了pause为打开就播放视频
+ mpv.conf 80行，修改了demuxer-max-bytes为300MiB
+ mpv.conf 224行，修改为默认开启了mvtools-2x.vpy

## 描述

> MPV由于历史遗留问题放在机械硬盘，而播放视频在固态，打开视频为 1080P H265 mp4。

1. 打开视频不做任何变动，回车进入全屏，在播放一定时间(3-50min)后，某一刻开始GPU的占用率会在任务管理器突然从20%飙升至100%。
2. 此时如果手速够快，强制结束mpv任务，一切恢复正常。反之稍微挺几秒，系统会全面死机，但不会触发蓝屏只能手动强制关机。
3. 触发时间虽然不确定，但最终触发频率都为100%，我本机已死机4次。

## 补充

**我并不能确定该崩溃由MPV本身所引发，还是脚本不兼容导致。**

**作者有如其他需要可以在回复中指出，类似所看视频，整体mpv的打包等，我会尽量提供。**

**Comment by hooke007** [comment]
用 `--no-config` 或者纯净模式测试，如果依然存在，则向mpv汇报

**Comment by jerryfangr** [comment]
这玩意测试成本太高，我已与自己达成和解，圆润的滚到了mpvnet。

晚上我看视频开播放器点到了mpv，结果新版mpv又支持lazy的配置组件了，突然觉得这说不定是个旧版mpv下特定视频下的小概率事件………

从我使用者的角度，问题已不存在，作者自己看需求决定是否关闭这个issue吧。

顺路问下 mpvnet 6.0.0.0 怎么默认开启类似 mvtools的滤镜，手册上没找到，说明指向的是个官方mpv的文档。

**Comment by hooke007** [comment]
编辑器里不是有一个默认的vf选项吗
