### ISSUE TITLE
有办法把底下的黑色遮罩改为透明吗？挡着字幕了

### ISSUE THREAD

**Issue by ttybamx** [hooke007/MPV_lazy#147]
![image](https://user-images.githubusercontent.com/47039282/178274491-cda90ccf-9e96-4c21-af4a-2f5c090b3f07.png)

**Comment by hooke007** [comment]
https://github.com/hooke007/MPV_lazy/blob/3601dd1f2adafd5eeb80afe8b2996b9af36493d6/portable_config/scripts/osc_lazy.lua#L594
bord低于50太多就看不清图标了

**Comment by ttybamx** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by hooke007** [comment]
https://github.com/hooke007/MPV_lazy/commit/cf8154172610c007d5f135f2d3a68685a7c809c1#diff-1b448988b9f4c2b2465ae6af2d11576739bbf55f3dd97342cbac1c458ff154e5

已通过此提交支持用户自定义阴影高度
