### ISSUE TITLE
反交错

### ISSUE THREAD

**Issue by sailing178** [hooke007/MPV_lazy#154]
MPV的反交错效果比pot差很多，是不是配置有什么问题

**Comment by sailing178** [comment]
![Quicker_20220718_225650](https://user-images.githubusercontent.com/89731041/179540626-29355354-de3d-4a6e-9dd9-d077bf7006fd.png)
![mpv](https://user-images.githubusercontent.com/89731041/179540633-fc081fa9-f48d-446e-bfda-f50e761edf9b.png)

图1为pot默认反交错设置，图2为mpv反交错快捷键D

**Comment by hooke007** [comment]
你需要一个我能复现的样本，只有图片我无法知道发生了什么

**Comment by hooke007** [comment]
无法复现的你的问题，你确定已经 `d` 开启去隔行？ ( `D` 是去色带)

![Snipaste_2022-07-18_23-17-59](https://user-images.githubusercontent.com/41094733/179626821-cefd95ef-8e7f-46c7-a484-6c55eb60a2bd.jpg)

**Comment by hooke007** [comment]
至于播放不流畅的问题，看日志是文件本身的问题。
可以临时用 `correct-pts=no` 修正它。

**Comment by sailing178** [comment]
correct-pts=no实测有用，感谢

![01 mp4 - mpv 114228](https://user-images.githubusercontent.com/89731041/179659941-c34eb1d1-d579-49cc-87b8-63b653c76146.png)
但是我把反交错快捷键改动为a，仍然跟没开一样，跟你这个效果不一样

**Comment by sailing178** [comment]
##⇘⇘在(shift+)i键的第一页查看vf/af的启用列表，第二页是glsl/hook的加载列表，第四页是静态键位绑定列表
##任何着色器和滤镜都可以设置成自动加载模式而无需每次手动装载，详见 mpv.conf 中“脚本 滤镜 着色器”的部分
##自定义快捷键的规则见手册 [05]

################
## 着色器列表 ##
################

##⇘⇘第三方着色器的详细介绍见手册 [01]

##开启/关闭 单项：KrigBilateral（速度较慢，高级色度还原，极高质量但感知很弱）
 CTRL+1               change-list glsl-shaders toggle "~~/shaders/KrigBilateral.glsl"
##开启/关闭 单项：AMD-FSR（速度很快，放大到目标分辨率，伴随对比度自适应锐化）
 CTRL+2               change-list glsl-shaders toggle "~~/shaders/AMD-FSR.glsl"
##开启/关闭 单项：RAVUzr3（速度一般，放大到目标分辨率，轻微锐化）
 CTRL+3               change-list glsl-shaders toggle "~~/shaders/ravu-zoom-r3.glsl"
##开启/关闭 单项：Anime4k-restore（速度快，无缩放，重建线条）
 CTRL+4               change-list glsl-shaders toggle "~~/shaders/Anime4K_Restore_CNN_M.glsl"
##开启/关闭 单项：Anime4k-GAN（速度快，两倍放大，感知略强）
 CTRL+5               change-list glsl-shaders toggle "~~/shaders/Anime4K_Upscale_GAN_x2_M.glsl"
##开启/关闭 单项：FSRCNNX8041（速度较慢，两倍放大，比较忠于原始画面）
 CTRL+6               change-list glsl-shaders toggle "~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"
##开启/关闭 单项：自适应锐化（速度一般，无缩放）
 CTRL+7               change-list glsl-shaders toggle "~~/shaders/adaptive-sharpen.glsl"
##开启/关闭 单项：NNEDI3-64（速度很慢，两倍放大，忠于原始画面）
 CTRL+8               change-list glsl-shaders toggle "~~/shaders/nnedi3-nns64-win8x4.glsl"

##覆盖式替换 组合：Anime4k的"DTDD"（速度较快，无缩放，加深线条+细化线条+中位降噪+高斯解糊，主观感知强）
 CTRL+9               change-list glsl-shaders set "~~/shaders/Anime4K_Darken_HQ.glsl;~~/shaders/Anime4K_Thin_HQ.glsl;~~/shaders/Anime4K_Denoise_Bilateral_Mode.glsl;~~/shaders/Anime4K_Deblur_DoG.glsl"
##覆盖式替换 组合：双SSIM（速度一般，辅助内建算法进行放大缩小）
 CTRL+0               change-list glsl-shaders set "~~/shaders/SSimSuperRes.glsl;~~/shaders/SSimDownscaler.glsl"

##清空所有已加载的着色器
 CTRL+`               change-list glsl-shaders clr "" # 清空列表（视频着色器）



##############
## 滤镜列表 ##
##############

##⇘⇘很多滤镜不支持 无-copy 的纯硬解方式（即 hwdec=xxxx )，最好使用 hwdec=no 或 hwdec=xxxx-copy 获得更好的兼容性
##滤镜的语法说明见手册 [03]

##VS补帧脚本只能同时启用一个，启用另一个前先关闭其他。其它未列出的方案按需添加修改 <shift 1、2、3、4、5>
##开启/关闭 mvtools 补帧通用版（推荐方案）
 !                    vf toggle vapoursynth="~~/vs/mvtools-std.vpy"        # 开/关 补帧
##开启/关闭 mvtools 补帧快速版（低开销推荐方案）
 @                    vf toggle vapoursynth="~~/vs/mvtools-fast.vpy"       # 开/关 补帧（低质量）
##开启/关闭 svpflow 倍帧2d动画方案（更适合10bit/vfr动态帧率视频）[在软解下svpflow不支持10bit中间处理]
 SHARP                vf toggle vapoursynth="~~/vs/svpflow-2x.vpy"         # 开/关 补帧
##开启/关闭 svpflow 补帧8bit方案（低开销推荐方案）
 $                    vf toggle vapoursynth="~~/vs/svpflow-8b.vpy"         # 开/关 补帧（低质量）
##开启/关闭 svpflow 补帧高级方案（坛友的自用脚本）
 %                    vf toggle vapoursynth="~~/vs/svpflow-Starlight.vpy"  # 开/关 补帧（高质量）

##开启/关闭 强制片源的色阶标记为16-235 （少数片源存在压制后色彩范围标记错误，具体表现在背景纯黑显灰色/底色纯白却发绿，常见于野路子的小黄片） <shift 6>
 ^                    vf toggle format=colorlevels=limited                 # 开/关 标记动态范围为有限
##开启/关闭 增加黑边（适用于2.35:1的片源适配16:9的字幕） <shift 7>
 &                    vf toggle pad=aspect=16/9:x=-1:y=-1                  # 开/关 填充16:9的黑边并居中

##开启/关闭 画面转动 <shift 8、9、0>
 *                    vf toggle rotate=angle=180*PI/180                    # 开/关 画面旋转180°
 (                    vf toggle vflip                                      # 开/关 画面垂直翻转
 )                    vf toggle hflip                                      # 开/关 画面水平翻转

##开启/关闭 伽马修正为2.2，可用于校色后的调整（默认ICC校正以BT.1886为目标曲线） <shift ->
 _                    vf toggle format=gamma=gamma2.2                      # 开/关 伽马修正2.2

##开启/关闭 znedi3---Yadifmod 反交错方案 <shift =>
 +                    vf toggle vapoursynth="~~/vs/deinterlace-std.vpy"    # 开/关 去隔行（软件/标准）

##清除所有已加载的视频滤镜 <shift `>
 ~                    vf clr "" # 清空列表（视频滤镜）



#############
## LUA脚本 ##
#############

##⇘⇘追加绑定外置脚本内建的快捷键方案，此处追加绑定的按键会与脚本内建的方案共存
##个别外置脚本的部分快捷键也可在 /script-opts/ 文件夹内找对应的配置文件进行修改，遵原作者介绍优先

##高级播放列表打开后，此时方向键切换与选中，回车播放，退格键移除，Esc键关闭（超时自动关闭或者再次按打开键也会关闭）
 F8                   script-binding playlistmanager/showplaylist        # 打开高级播放列表（替换原默认的简易OSD播放列表；超时自动或手动再次按下关闭）
 SHIFT+ENTER          script-binding playlistmanager/showplaylist        # 打开高级播放列表
 w                    script-binding load_plus/import_files              # 使用资源管理器加载文件（多选）
 W                    script-binding load_plus/import_url                # 使用PowerShell加载网址
 CTRL+w               script-binding load_plus/append_aid                # 使用资源管理器加载其它音轨
 ALT+w                script-binding load_plus/append_sid                # 使用资源管理器加载其它字幕
 e                    script-binding load_plus/append_vfSub              # 使用资源管理器加载/变更次字幕（滤镜型）
 E                    script-binding load_plus/toggle_vfSub              # 隐藏/显示 当前的次字幕（滤镜型）
 CTRL+e               script-binding load_plus/remove_vfSub              # 移除次字幕（滤镜型）
 CTRL+a               script-binding cycle_adevice/back                  # 切换到上一个音频设备
 ALT+a                script-binding cycle_adevice/next                  # 切换到下一个音频设备
 SHIFT+DEL            script-binding osc_lazy/visibility                 # 切换osc_lazy的可见性
 

##⇘⇘MPV内部自带的LUA脚本

 i                    script-binding stats/display-stats           # 临时显示统计信息（此时01234翻页，024页可方向上下键滚动查看）
 I                    script-binding stats/display-stats-toggle    # 开/关 常驻显示统计信息
 `                    script-binding console/enable                # 进入控制台（此时Esc退出）
 DEL                  script-binding osc/visibility                # 切换 内置OSC的可见性


##############
## 其它操作 ##
##############

##⇘⇘剩余按键的对应操作，应防止出现同样的键位（组合）
##左中右分别为 —— 键值/键位名（必要）；触发操作名（必要）；注释的中文解释（可删）
##注意如果已经在主设置文件中使用了参数 --no-input-builtin-bindings 则无需针对不想要触发的键位实施 "ignore"
##完整的mpv内建快捷键方案见 https://github.com/mpv-player/mpv/blob/master/etc/input.conf 全部功能见 https://mpv.io/manual/master/#input-conf

##⇘⇘鼠标

#MBTN_LEFT            ignore                       # <无操作> [左键-单击]
 MBTN_LEFT_DBL        cycle fullscreen             # 切换 全屏状态 [左键-双击]
 MBTN_BACK            playlist-prev                # 切换到列表中的上个文件 [后退键]
 MBTN_FORWARD         playlist-next                # 切换到列表中的下个文件 [前进键]
#MBTN_MID             ignore                       # 默认没给定义但是很多人用，要用建议清空下两条操作名（易误触）[中键（按压滚轮）]

 WHEEL_UP             seek -10                     # 后退10秒 [滚轮-向上]
 WHEEL_DOWN           seek  10                     # 前进10秒 [滚轮-向下]
#WHEEL_LEFT           ignore                       # <无操作> [滚轮-向左]
#WHEEL_RIGHT          ignore                       # <无操作> [滚轮-向右]

##⇘⇘键盘

 q                    quit                         # 关闭MPV程序
 Q                    quit-watch-later             # 关闭MPV程序 稍后观看（保存当前文件状态）
 o                    show-progress                # 临时显示时间码/进度条
 P                    show-progress                # 临时显示时间码/进度条
 O                    no-osd cycle-values osd-level 3 1 # 常驻显示时间码

 1                    add contrast -1              # 对比度 -
 2                    add contrast  1              # 对比度 +
 3                    add brightness -1            # 明度 -
 4                    add brightness  1            # 明度 +
 5                    add gamma -1                 # 伽马 -
 6                    add gamma  1                 # 伽马 +
 7                    add saturation -1            # 饱和度/纯度 -
 8                    add saturation  1            # 饱和度/纯度 +
 9                    add hue -1                   # 色相 -
 0                    add hue  1                   # 色相 +
 CTRL+BS              set contrast 0 ; set brightness 0 ; set gamma 0 ; set saturation 0 ; set hue 0 # 重置（视频）均衡器

##当输出旋转之后，垂直方向因跟随输出方向的变化而改变。输出旋转操作会启动缩略图重建进程
##输出旋转可能产生色度升频的bug，可改 mpv.conf 中 --cscale=bilinear 或启用去色带或使用软解解决
 CTRL+LEFT            cycle-values video-rotate "0" "270" "180" "90" # 视频输出逆时针旋转90°
 CTRL+RIGHT           cycle-values video-rotate "0" "90" "180" "270" # 视频输出顺时针旋转90°

 ALT+0                cycle-values current-window-scale "0.5" "1.0" "1.5" # 快速缩放窗口大小
 ALT+`                set current-window-scale  1.0    # 重置窗口大小为一倍
 ALT+1                add current-window-scale -0.1    # 窗口 -
 ALT+2                add current-window-scale  0.1    # 窗口 +
 ALT+9                cycle-values panscan "0.0" "1.0" # 视频缩放以适合/填充窗口
 ALT+-                add video-zoom  -0.1         # 视频缩放 -（窗口不变）
 ALT+=                add video-zoom   0.1         # 视频缩放 +（窗口不变）
 ALT+LEFT             add video-pan-x -0.1         # 视频移动 ←（窗口不变）
 ALT+RIGHT            add video-pan-x  0.1         # 视频移动 →（窗口不变）
 ALT+UP               add video-pan-y -0.1         # 视频移动 ↑（窗口不变）
 ALT+DOWN             add video-pan-y  0.1         # 视频移动 ↓（窗口不变）
 ALT+BS               set video-zoom 0 ; set video-pan-x 0 ; set video-pan-y 0 # 重置视频的缩放与移动
 ALT+b                cycle border                 # 切换 窗口边框

 CTRL+v               cycle video                  # 切换视频轨
 p                    cycle pause                  # 切换 暂停/播放状态
 SPACE                cycle pause                  # 切换 暂停/播放状态 [空格键]
 CTRL+ALT+SPACE       stop                         # 停止
 T                    cycle ontop                  # 切换 置顶状态
 t                    set ontop yes                # 进入置顶状态
 f                    cycle fullscreen             # 切换 全屏状态
 ENTER                set fullscreen yes           # 进入全屏状态 [回车键]
 ESC                  set fullscreen no            # 退出全屏状态
 l                    ab-loop                      # 设置/清除 A-B循环点
 L                    cycle-values loop-file "inf" "no" # 切换 当前文件循环播放
 ,                    frame-back-step              # （暂停）帧步退
 .                    frame-step                   # （暂停）帧步进
 CTRL+,               add chapter -1               # 章节 -
 CTRL+.               add chapter  1               # 章节 +
 <                    playlist-prev                # 列表中的上个文件
 >                    playlist-next                # 列表中的下个文件
 LEFT                 seek -5                      # 后退05秒 [方向左键]
 SHIFT+LEFT           seek -1 exact                # 后退01秒（精确）
 RIGHT                seek  5                      # 前进05秒 [方向右键]
 SHIFT+RIGHT          seek  1 exact                # 前进01秒（精确）
 UP                   seek -60                     # 后退60秒 [方向上键]
 DOWN                 seek  60                     # 前进60秒 [方向下键]
 [                    add speed -0.1               # 播放速度 -（最小0.01）
 ]                    add speed  0.1               # 播放速度 +（最大100）
 {                    multiply speed 0.5           # 播放速度 半减
 }                    multiply speed 2.0           # 播放速度 倍增
 BS                   set speed 1.0                # 重置播放速度 [退格键]

 a                    cycle deinterlace            # 切换 去隔行状态
 D                    cycle deband                 # 切换 去色带状态
 j                    add sharpen -0.1             # 清晰度 -（勿低于-1）
 k                    add sharpen  0.1             # 清晰度 +（勿高于1）
 CTRL+h               cycle-values hwdec "auto" "auto-copy" "no" # 切换 优先硬解//硬解+//软解

##快速在指定的音频输出设备间切换、设备名的获取见发布页FAQ或文档 https://mpv.io/manual/master/#options-audio-device
#A                    cycle-values audio-device "wasapi/{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}" "wasapi/{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}"
 -                    add volume -1                # 音量 -
 =                    add volume  1                # 音量 +
 m                    cycle mute                   # 切换 静音状态
 ALT+c                add aid -1                   # 音轨 上一个
 ALT+v                add aid  1                   # 音轨 下一个
 c                    add audio-delay -0.1         # 音频同步 预载100ms
 v                    add audio-delay  0.1         # 音频同步 延迟100ms
 z                    add sub-delay -0.1           # 字幕同步 预载100ms
 x                    add sub-delay +0.1           # 字幕同步 延迟100ms
 SHIFT+BS             set audio-delay 0 ; set sub-delay 0 # 重置音频与字幕同步
 Z                    add sub-scale -0.1           # 字幕缩放 -
 X                    add sub-scale +0.1           # 字幕缩放 +
 CTRL+z               add sub-pos -1               # 字幕移动 ↑
 CTRL+x               add sub-pos +1               # 字幕移动 ↓
 ALT+z                add sid -1                   # 字幕轨 上一个
 ALT+x                add sid  1                   # 字幕轨 下一个
 ALT+Z                add secondary-sid -1         # 次字幕轨（原生） 上一个
 ALT+X                add secondary-sid  1         # 次字幕轨（原生） 下一个
##当前原生双字幕的问题与另一种实现多字幕的方案： https://github.com/hooke007/MPV_lazy/discussions/61
 CTRL+ALT+z           cycle sub-ass-vsfilter-blur-compat
## 如果当前用的ASS字幕存在的异常拉伸与变形就临时切换 https://github.com/bubblesub/bubblesub/issues/85

 s                    screenshot                   # 截屏（有字幕、有OSD） 输出原始分辨率
 S                    screenshot video             # 截屏（无字幕、无OSD） 输出原始分辨率
 CTRL+s               screenshot window            # 截屏（有字幕、有OSD） 输出实际分辨率
 ALT+s                screenshot each-frame        # 截屏（逐帧）
##截屏（逐帧），再次执行该命令停止。默认方式等同"s"，可以在"each-frame"后添加" video"或" window"修改逐帧截图的方式。可能需要在mpv.conf使用 --framedrop=no 来避免截图丢帧与重复

**Comment by sailing178** [comment]
a                    cycle deinterlace            # 切换 去隔行状态
 D                    cycle deband                 # 切换 去色带状态
 j                    add sharpen -0.1             # 清晰度 -（勿低于-1）
 k                    add sharpen  0.1             # 清晰度 +（勿高于1）
 CTRL+h               cycle-values hwdec "auto" "auto-copy" "no" # 切换 优先硬解//硬解+//软解

**Comment by sailing178** [comment]
[portable_config.zip](https://github.com/hooke007/MPV_lazy/files/9137329/portable_config.zip)
实测重新下载你的安装包是没有问题的，能帮我看看我的配置文件有什么问题吗

**Comment by sailing178** [comment]
还有一点，我在配置文件设置默认打开反交错，这对逐行扫描的文件会有什么影响？望解答

**Comment by hooke007** [comment]
> 还有一点，我在配置文件设置默认打开反交错，这对逐行扫描的文件会有什么影响？望解答
 Note that this will make video look worse if it's not actually interlaced.

**Comment by hooke007** [comment]
一种简陋的自动反交错方式。
最终因考虑到它的限制性而撤销了这个提交，仅供参考

https://github.com/hooke007/MPV_lazy/blob/18a84531ba5e2a4ced2657067aed15087e5ad325/portable_config/profiles.conf#L103-L114
