### ISSUE TITLE
系统默认播放器

### ISSUE THREAD

**Issue by sailing178** [hooke007/MPV_lazy#157]
有没有比较优雅的方式实现视频文件双击后直接打开mpv，例如恒星播放器之类的直接设置默认播放器，而不是所谓的打开方式。mpv文件关联仅仅适用于打开方式，每重装一次系统就需要重复操作打开方式，很不方便

**Comment by hooke007** [comment]
win10上不是注册完可以直接控制面板改成默认视频播放器？

**Comment by sailing178** [comment]
![设置 003029](https://user-images.githubusercontent.com/89731041/182036188-955d90a7-ac13-46b3-81aa-9033d9fd2bc8.png)
除了点开mpv看到关联文件以外，我不会操作。双击打开mp4仍然需要使用打开方式

**Comment by hooke007** [comment]
win11砍掉了这个功能

**Comment by sailing178** [comment]
Get-AppxPackage *photo* | Remove-AppxPackage

删除默认照片查看器即可，微软的作品
