### ISSUE TITLE
新版mvtools-std.vpy产生明显延迟与卡顿

### ISSUE THREAD

**Issue by CaptainRay1993** [hooke007/MPV_lazy#161]

**Comment by hooke007** [comment]
最新的提交只是避免了api4无法运行的错误，并没有调节过mvtools-std的任何效果参数

**Comment by CaptainRay1993** [comment]
我刚刚测试了一下，的确不是vpy脚本的问题，应该是更新后Anime4K_Restore_CNN_M和mvtools脚本共用时都会出现大量frame drops导致卡顿。无论是mvtools-2x还是std，只要同时开启Anime4K_Restore_CNN_M都会出现displayfps大幅降低的情况，但是单独开Anime4K_Restore_CNN_M或者换成其它shader貌似都没问题，不知道具体原因。我attach了几种测试环境下的统计信息截图，你可以参考一下。
![一切正常：anime4k_cnn_m(1)](https://user-images.githubusercontent.com/85709888/184889318-58c1a1e5-abbe-4717-bd97-0a59322f1b5e.png)
![一切正常：anime4k_cnn_m(2)](https://user-images.githubusercontent.com/85709888/184889332-5c543871-1ed4-42d3-94c9-ad2fac3b251e.png)
![一切正常：mvtools-2x(1)](https://user-images.githubusercontent.com/85709888/184889340-297e22e8-d56a-45a0-8285-fc85a3e3a857.png)
![一切正常：mvtools-2x(2)](https://user-images.githubusercontent.com/85709888/184889343-72373e80-f38e-484d-9fc7-250cd88c44a7.png)
![一切正常：mvtools-std(1)](https://user-images.githubusercontent.com/85709888/184889348-a7854174-fda1-4d1a-a64e-b45934033ca5.png)
![一切正常：mvtools-std(2)](https://user-images.githubusercontent.com/85709888/184889355-51250d32-568d-4c23-8307-2d8ed811bb0e.png)
![一切正常：mvtools-std+KrigBilateral(1)](https://user-images.githubusercontent.com/85709888/184889362-0d3dfea9-0c7e-4192-a13c-08b8d68f9c2d.png)
![一切正常：mvtools-std+KrigBilateral(2)](https://user-images.githubusercontent.com/85709888/184889368-6d2d6e84-f8df-481e-a60e-59835e889b7d.png)
![掉帧严重：mvtools-2x+anime4k_cnn_m(1)](https://user-images.githubusercontent.com/85709888/184889375-7010e072-22a9-4acc-9e5a-3df6a3a39d7c.png)
![掉帧严重：mvtools-2x+anime4k_cnn_m(2)](https://user-images.githubusercontent.com/85709888/184889382-83710922-33a4-47b7-bff2-6a9cd6586934.png)
![掉帧严重：mvtools-std+anime4k_cnn_m(1)](https://user-images.githubusercontent.com/85709888/184889387-e4b99e63-ee7e-4a29-8e8f-ad8255573eb3.png)
![掉帧严重：mvtools-std+anime4k_cnn_m(2)](https://user-images.githubusercontent.com/85709888/184889397-f813df74-aec5-4828-a8c8-34020581a244.png)

**注：我的mpv是最新8.14号的版本，然后mpv.conf里的interpolation设置经我实验不影响测试结果**

**Comment by hooke007** [comment]
本质就是性能不足。
60fps的帧间隔远小于24fps，无法在该段时间内完成一帧的渲染

**Comment by CaptainRay1993** [comment]
> 本质就是性能不足。 60fps的帧间隔远小于24fps，无法在该段时间内完成一帧的渲染

我一直都是mvtools-std + Anime4K_Restore_CNN_M的组合，但是我之前没有出现这个问题。我再用老版本的mvtools-std试试

**Comment by hooke007** [comment]
。。。所以一开始就是讲了修复了无法运行的错误

**Comment by CaptainRay1993** [comment]
应该是中途某个版本更新后失效的吧，主要是最开始用更老版本的时候我check过应该是正常的，后面更新后由于我对帧数不是太敏感就没感觉出来。。。

**Comment by CaptainRay1993** [comment]
> 应该是中途某个版本更新后失效的吧，主要是最开始用更老版本的时候我check过应该是正常的，后面更新后由于我对帧数不是太敏感就没感觉出来。。。
