### ISSUE TITLE
Mixing audio tracks with the load_plus lua script does nothing

### ISSUE THREAD

**Issue by 57o** [hooke007/MPV_lazy#162]
I'm not sure where the issue is, I've tried both the original one and the one that I translated into English and neither of them do anything.

**Comment by hooke007** [comment]
Log?

**Comment by 57o** [comment]
all normal but https://imgur.com/a/8Qnd38j

**Comment by 57o** [comment]
Ok I'm actually stupid I realized my issue, somehow there was the information of the script at the top of it (487 lines, however big) and that's where the error comes from. Not sure how that happened but I got rid of it and the script works, flawlessly. I was just wondering now if there would be a way to select 3 or more tracks instead of 2, for the very rare use case that it might be needed. Tysm for this script though

**Comment by hooke007** [comment]
My solution is clumsy, I have no idea how to implement the flexible multi-tracks marks.
