### ISSUE TITLE
项目性质变更

### ISSUE THREAD

**Issue by hooke007** [hooke007/MPV_lazy#168]
虽然这个仓库依然保持更新，但是部分脚本和大部分着色器我很久不使用了，我自己用的设置也和懒人包呈现的有差异。
考虑到这个项目的目的，直接套用我的本地更改删改大量文件显然不合适。

可能的下一步的工作：
- [x] 发布基于旧仓库结构的最后一版懒人包（[【旧版快速说明】](https://hooke007.github.io/mpv-lazy/mpv_lazy_d00.html)）
 https://github.com/hooke007/MPV_lazy/releases/tag/20220903
- [x] 使用 [**lite分支**](https://github.com/hooke007/MPV_lazy/tree/lite) 存放个人设置
  - [x] 发布基于该分支的新版整合包（内容极度精简，如不适应建议使用旧版懒人包）
- [x] ！！！本仓库的主分支不再作为个人设置而是历史存档（**这将产生脚本功能重合或冲突**）！！！
  - [x] 迁移杂物间的文件进原主设置区
  - [x] 修正维基的对应内容
  - [x] 修改部分主观性的设置，使主设置和脚本设置相互独立（**这将产生脚本与核心设置冲突**） 
 https://github.com/hooke007/MPV_lazy/commit/7613edf0871dbed29bb39931c6cad80b55d40eb4
- [x] 转换为模板库
  - [x] 启用 [**obs分支**](https://github.com/hooke007/MPV_lazy/tree/obs) 作为原个人设置的额外备份（在克隆模板库时选择所有branch，可以以旧仓库结构作为你的起始提交）
<img src="https://user-images.githubusercontent.com/41094733/190601416-d86a4084-63e9-41ca-8eb0-b587bf0c3f6d.jpg" width=350> <img src="https://user-images.githubusercontent.com/41094733/190601421-f4d8f84b-def1-4bb9-8b89-7b9c3375c0b2.jpg" width=350>

转型基本完成，后续的变动为演示而不是实际使用服务：
- [x] 拆分 [旧的input.conf](https://github.com/hooke007/MPV_lazy/blob/obs/portable_config/input.conf) 为多个文件以展示不同类型的快捷键绑定（**这可能将产生键位冲突**）
 https://github.com/hooke007/MPV_lazy/commit/92b0053256651e4b4375b6cf131dd1351de51a9c
- [x] 删除大多数注释符，以便于代码高亮利于阅读，并进一步清理部分偏好性预设（**由于可能与默认值相同，这将产生大量多余的重复设置**）
 [旧的mpv.conf](https://github.com/hooke007/MPV_lazy/blob/obs/portable_config/mpv.conf) https://github.com/hooke007/MPV_lazy/commit/639c5c6543ef2db58798e9e15f107f1cf843a261 https://github.com/hooke007/MPV_lazy/commit/7ecd7936d16ac28487705a557f2fc678bf6f10ac
 [旧的脚本选项](https://github.com/hooke007/MPV_lazy/tree/obs/portable_config/script-opts) https://github.com/hooke007/MPV_lazy/commit/a305bf3a99b6b2e085b2a7dd7d6ec442c1427f6f
- [x] 主页补充关于分支说明的内容

**Comment by ShaddockCyan** [comment]
对您的个人设置很感兴趣，如果可以希望可以像mpv-lazy这个优秀的项目一样开源以供使用

**Comment by hooke007** [comment]
> 对您的个人设置很感兴趣

只是设置没啥神秘的。。反正就那几个选项改来改去
_与其说差异，用大幅精简形容更合适_

当前的仓库的内容和结构和懒人包完全对应；
按计划修改完毕后，以后发布的整合包，不会像现在的懒人包一样注释说明那样齐全，组件也只我自用的部分。

**Comment by skiqing** [comment]
大佬辛苦了！

**Comment by hooke007** [comment]
> 对您的个人设置很感兴趣

Done. https://github.com/hooke007/MPV_lazy/tree/lite

**Comment by ShaddockCyan** [comment]
> > 对您的个人设置很感兴趣
> 
> Done. https://github.com/hooke007/MPV_lazy/tree/lite

感谢
