### ISSUE TITLE
!help menu not working 

### ISSUE THREAD

**Issue by omaru-ok** [hooke007/MPV_lazy#179]
![image](https://user-images.githubusercontent.com/108952834/189479252-0b2d3efb-26cc-4728-b207-b346947e2a84.png)
what i have done wrong?

**Comment by omaru-ok** [comment]
and also thumbinal_worker not workign too

**Comment by hooke007** [comment]
ref https://github.com/hooke007/MPV_lazy/discussions/60

you might haven't installed deps.

**Comment by omaru-ok** [comment]
what about thumbnails not working ?

**Comment by hooke007** [comment]
https://github.com/hooke007/MPV_lazy/blob/main/portable_config/script-opts/thumbnailer.conf

Because it was disabled (default).

**Comment by omaru-ok** [comment]
> https://github.com/hooke007/MPV_lazy/blob/main/portable_config/script-opts/thumbnailer.conf
> 
> Because it was disabled (default).

what do u mean? 

and what i have to do  , do i copy that thumbnailer.conf? 

btw i don't know chinese :(

**Comment by hooke007** [comment]
Thumbnailer worker is my fork of https://github.com/deus0ww/mpv-conf/tree/master/scripts
It works perfectly here. Not sure what happended in your side.

> btw i don't know chinese :(

If you use mpv-lazy, it should work without any issue. You could also try to use the some of scripts from the repo. But sry, there is no plan to fully support for Internationalisation.
