### ISSUE TITLE
上下文菜单中的截屏功能的实用性改进

### ISSUE THREAD

**Issue by Youxikong** [hooke007/MPV_lazy#196]
我不想笑但实在忍不住，菜单会被截入画面。截屏有关设置我只修改了保存的格式，其他没动。
![image](https://user-images.githubusercontent.com/26603498/196193737-111545d6-b5b5-4259-91a9-8df055a30eb3.png)

**Comment by hooke007** [comment]
这个问题怎么说呢。。
这确实符合 `screenshot window` 的预期，但是当前的release版本我没给出（绑定）按键提示（下个版本会修改，参见lite分支的提交）

我不喜欢 `screenshot video` 的截图结果，你也可以选择重绑定到对应命令。
https://github.com/hooke007/MPV_lazy/blob/bba8504889d01cd46b62446bdbf309c4d0780109/portable_config/input_easy.conf#L125-L127

**Comment by Youxikong** [comment]
我自己绑个按键吧。这个不适合放在右键菜单。

**Comment by hooke007** [comment]
很多功能都不适合用菜单触发（例如均衡器），依然选择放在那里的原因是菜单的一个功能是按钮提示

**Comment by hooke007** [comment]
尝试了一圈没有找到完美的解决方案，当前的提交只是堪用的水平。

**Comment by dyphire** [comment]
比起直接修改 uosc.lua 脚本，我更推荐使用第三方脚本来实现延时命令。比如此脚本：[delay-command.lua](https://github.com/CogentRedTester/mpv-scripts/blob/master/delay-command.lua)
针对这一问题的使用案例：
```
s                script-message delay-command 0.3 screenshot subtitles                  #menu: 视频 > 截屏 > 同源尺寸-有字幕-有OSD-单帧
S                screenshot video                                                       #menu: 视频 > 截屏 > 同源尺寸-无字幕-无OSD-单帧
CTRL+s           script-message delay-command 0.3 screenshot window                     #menu: 视频 > 截屏 > 实际尺寸-有字幕-有OSD-单帧
ALT+s            script-message delay-command 0.3 screenshot subtitles+each-frame       #menu: 视频 > 截屏 > 同源尺寸-有字幕-有OSD-逐帧
ALT+S            screenshot video+each-frame                                            #menu: 视频 > 截屏 > 同源尺寸-无字幕-无OSD-逐帧
CTRL+S           script-message delay-command 0.3 screenshot window+each-frame          #menu: 视频 > 截屏 > 实际尺寸-有字幕-有OSD-逐帧
```

**Comment by hooke007** [comment]
> 尝试了一圈

你说的这个也属于我说的废弃方案。一开始我是在input_plus里加新命令然后uosc去绑定。
但是这个条目属于我的默认菜单内容，捆绑一个外部脚本的命令不理想，相当于强制要安装另外的脚本。（虽然之前我已经做过了这样的反面案例）
另外延迟零点几秒截屏这种需求实在过于奇葩，也是为了uosc才专门搞了这样的命令，放在uosc脚本内成了最终的方案。

**Comment by dyphire** [comment]
这种考虑可以理解。如果没有其他延迟命令需求的话单独为截屏这一个案例引入一个新的脚本确实不太合适

**Comment by hooke007** [comment]
我基本满意当前的状态。
@Youxikong 请测试

**Comment by Youxikong** [comment]
简单试了下，截图已经不包含菜单了。

**Comment by hooke007** [comment]
一个可行的完美途径参考 https://github.com/tomasklaen/uosc/commit/c2b10b6eadd9b2754d4e4a0fc2529b29a34fc61a
先不管了，目前的处理够用了
