### ISSUE TITLE
请问怎么设置成鼠标左键播放/暂停播放？

### ISSUE THREAD

**Issue by mark-jiang-1470** [hooke007/MPV_lazy#213]
我在配置文件里添加了，WHEEL_LEFT        cycle pause，但是好像没有用

**Comment by hooke007** [comment]
WHEEL是滚轮

https://github.com/hooke007/MPV_lazy/blob/96819d9bd2b550f53bb69839c8ae1f96fc91d617/portable_config/input_easy.conf#L17
