### ISSUE TITLE
加载外部音轨快进快退时画面停滞几秒

### ISSUE THREAD

**Issue by Frozen1084** [hooke007/MPV_lazy#224]
我下载油管视频都是不合并视频音频，让mpv自动加载同名的外部音轨。大部分的高清视频都没有问题，但某些类型的视频快进快退时，会画面停滞几秒，等到音画同步了才继续播放。

比如这个，下载它的m4a音频和1080Pmp4，播放，调整进度到一半，然后按住"Left"键快退个6、7次，就会先出现几秒无声的正常画面，然后画面卡住，出现几秒的正常声音，直至二者同步了，画面和声音才同时正常。

https://www.youtube.com/watch?v=eu0HeFG_xqI

用的是 mpvnet-CM 默认配置。
我电脑播放4K电影这样快进快退没有问题，应该不是性能瓶颈。
有时快进也会出现这样的问题。
似乎问题只出现在这种MP4配M4A的视频。播放4K的webm配M4A，快进快退都没有这种问题。

**Comment by hooke007** [comment]
无关乎前端。上游的问题应该向正确的仓库报告

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/issues/1824#issuecomment-93369730

**Comment by Frozen1084** [comment]
好的，谢谢。
这个问题使用"hr-seek=yes"参数就消失了，但相应的快进退4K视频就变得卡顿起来。真是没有完美的解决方案。
而PotPlayer就没有这样的问题。

**Comment by hooke007** [comment]
刚没细看，现在我重新看了一下你的问题描述。问题表现不一致，我不存在画面停滞的问题。
但是无论如何，这里不是正确报告mpv问题的地方

**Comment by Frozen1084** [comment]
主要是我没把这当成bug，我认为会是有什么参数使用不恰当，或者用某个参数就可以解决。

**Comment by Frozen1084** [comment]
我下载了最新版本的MPV_lazy，确实没有停滞问题。
但mpvnet-CM有明显的停滞，只要你多按住左右方向键一段时间，都会出现画面停滞，只有声音的现象。

另外一个问题是配置。从文件菜单>打开方式找到MPV_lazy打开视频，和在管理器运行mpv.exe，然后拖个视频上去，两个打开方式使用的似乎是不同的配置。能统一下配置吗？

**Comment by Frozen1084** [comment]
配置问题似乎是系统bug，我是同时使用官方mpv和mpv-lazy的，打开方式的菜单里是有mpv项的，这时通过"选择其他应用"找到的mpv_lazy，因为它的进程名也是mpv.exe，系统就直接调用了官方mpv。所以即使我手动选择了mpvlazy，系统也仍旧只会用官方mpv。

**Comment by hooke007** [comment]
你搞错了几个东西，官方的exe是近期才有的，但那是用来调试的。

打开方式的问题，重新运行注册脚本覆盖旧项。我的编译版同样使用了shin版的封装和工具链。
如果打开方式项不是注册脚本产生的而是你手动设置程序路径造成的，尝试删除对应程序。

读取设置的问题。所有mpv默认读取appdata下的配置，windows平台特性允许优先并只读取portable_config，我的包利用此特性进行整合与发布，你可以参考官方手册手动迁移设置文件到对应的默认配置的位置。

**Comment by Frozen1084** [comment]
谢谢。
你是MPV_lazy和mpvnet-CM都无法复现1楼的问题吗？

**Comment by hooke007** [comment]
CM的内核版本和lazy不同步，尝试手动更新到最新内核测试

**Comment by Frozen1084** [comment]
啊抱歉，是我测试不严谨，用一楼的视频测试。lazy和net-cm都会卡画面。
