### ISSUE TITLE
视频截图不会抓取原始分辨率

### ISSUE THREAD

**Issue by Joyace** [hooke007/MPV_lazy#225]
视频截图不会抓取原始分辨率，而是屏幕分辨率，请问该如何修改？

**Comment by zhongfly** [comment]
https://github.com/hooke007/MPV_lazy/blob/main/portable_config/input_easy.conf#L125-L128

参考修改对应的快捷键试试

**Comment by Joyace** [comment]
> https://github.com/hooke007/MPV_lazy/blob/main/portable_config/input_easy.conf#L125-L128
> 
> 参考修改对应的快捷键试试

感谢  解决了

还有一个小问题，如何修改默认窗口不置顶

我修改了 `mpv.conf`
`
 ontop = no
`
还是没生效

用的这版
mpv-lazy-2022EX

**Comment by Joyace** [comment]
> > https://github.com/hooke007/MPV_lazy/blob/main/portable_config/input_easy.conf#L125-L128
> > 参考修改对应的快捷键试试
> 
> 感谢 解决了
> 
> 还有一个小问题，如何修改默认窗口不置顶
> 
> 我修改了 `mpv.conf` `ontop = no` 还是没生效
> 
> 用的这版 mpv-lazy-2022EX

解决了  在`profiles.conf`里

**Comment by hooke007** [comment]
截图没有抓取屏幕分辨率的功能，只有源分辨率和输出分辨率
