### ISSUE TITLE
问一些关于mpcvr的问题（大佬的mpcvr汉化项目没有issues，就在这边问了，大佬见谅）

### ISSUE THREAD

**Issue by RBHakureiReimu** [hooke007/MPV_lazy#232]
大佬，我这边有两台笔记本设备，显卡方面一台使用英伟达的2070MQ，一台使用截图里面的英特尔核显，在我这边在使用mpcvr的时候，在控制面板，视频渲染器都开启0-255，视频源也是0-255的前提下，mpcvr的颜色范围会被限制在16-235，我无论怎么更改设置都达不到大佬你的mpcvr汉化项目里面的0-255，画面对比madvr和mpv更是明显发灰，请问该如何解决呢？
![屏幕截图(1)](https://user-images.githubusercontent.com/45761551/203241772-8a330ef3-2bba-4856-85fb-48e590ca8c6f.png)

**Comment by hooke007** [comment]
那个项目有声明去哪里反馈问题
