### ISSUE TITLE
BT.601 to BT.709 [HD]

### ISSUE THREAD

**Issue by sun-shine-boy** [hooke007/MPV_lazy#241]
Hello, i want to know how to have this shader with mpv.net or your tool? i really love your work. All in one tool easy :) no need to dig around or do code but the feature is missing from MPC is BT.601 to BT.709 [HD] shader. can you somehow add this shader too?

**Comment by hooke007** [comment]
I haven't know anyone had tried to transfer this shader.
If you want to transfer the 601 source to 709 on the fly, it could be done by the video filter `vf=format=primaries=bt.709:convert=yes`

**Comment by sun-shine-boy** [comment]
Ty you are hero ♥

**Comment by sun-shine-boy** [comment]
tested it, it only works good with gpu and if you take gpu next the colors are not that good.

**Comment by sun-shine-boy** [comment]
Fixed it. in case you want to know how [ target-trc = 's-log1' ] also enabled the **icc profile auto: yes from the ui**

enabling icc profile auto yes with with vf=format=primaries=bt.709 didnt help but only with s-log1. anyway, thank you for your help. im looking for next releases.

**Comment by sun-shine-boy** [comment]
Sorry if i ask unrelated questions here. can't find a geek like you. in Potplayer there is an option call surface format: 32bit-floating point or 16-bit floating point when i enable this (using d3d11) the colors look decent but i have no idea how to do the same with mpv.net_CM or mpv itself.
Also, can't find anything related to this in mpv reference. do you know how can i have the same color experience with mpv?

**Comment by sun-shine-boy** [comment]
![mpv-shot0001](https://user-images.githubusercontent.com/39781890/208709508-5de208e4-da5a-4aa5-b618-e27521e80f29.jpg)
![pot](https://user-images.githubusercontent.com/39781890/208709560-c74ce146-d8fd-4baf-b2fb-8f8c87b767d7.png)

**Comment by hooke007** [comment]
Texture format should never affect colorlevels. Your potplayer is buggy.

**Comment by sun-shine-boy** [comment]
very good ty. but do u know how can mpv reproduce the same buggy color? the command i mean?

**Comment by hooke007** [comment]
There is no this bug in any other player i know.
