### ISSUE TITLE
查看图片问题

### ISSUE THREAD

**Issue by SONGjiemo** [hooke007/MPV_lazy#246]
查看图片，我发现是 轮播本目录下的图片，且轮播完就结束了。
我不知道能不能设置，
希望可以指定我一下。就是跟图片查看软件一样，点击就查看不要播放。

**Comment by hooke007** [comment]
这都不算问题。你开着播放自然它按照你的希望播放

**Comment by SONGjiemo** [comment]
> 这都不算问题。你开着播放自然它按照你的希望播放

我想知道如何设置他，指点一下吧

**Comment by hooke007** [comment]
至少应该基本熟悉一下mpv的基础参数

**Comment by SONGjiemo** [comment]
> 至少应该基本熟悉一下mpv的基础参数
小白鼠一个。哎还是用系统自带的算了
