### ISSUE TITLE
全屏播放时画面闪烁

### ISSUE THREAD

**Issue by Asukaaaaaa** [hooke007/MPV_lazy#250]
![image](https://user-images.githubusercontent.com/24503369/209783326-acfd58a7-2f6d-4892-88a9-c0694eb60e42.png)
发现开启全屏后显示帧率会暴涨到几百帧，然后画面频繁闪烁，如视频中所示

https://user-images.githubusercontent.com/24503369/209783839-c05fc6eb-f00a-4765-8651-21b58d33de0f.mp4

尝试用a卡驱动后台录制视频时会恢复到60帧并且显示正常，故用手机拍摄

显卡：rx6700xt
操作系统：windows11
软件版本：20221112

**Comment by hooke007** [comment]
看faq，你没有垂直同步
