### ISSUE TITLE
playlistmanager 的一个选项错误

### ISSUE THREAD

**Issue by PhyX-Meow** [hooke007/MPV_lazy#275]
https://github.com/hooke007/MPV_lazy/blob/f0a8af503b2744ddac5ba2e379f35087f1f545c3/portable_config/script-opts/playlistmanager.conf#L69

此处应为 resolve_url_titles
参考
https://github.com/jonniek/mpv-playlistmanager/blob/ae88b284411d1799d520e6b9b87a6608064290ea/playlistmanager.conf#L96

**Comment by hooke007** [comment]
查明是在最后几次同步时遗漏的，但我不打算修复它。
可能的后续计划是精简此脚本只保留核心的条目移动功能。

**Comment by dyphire** [comment]
playlistmanager 脚本近期的开发简直混乱，比如 https://github.com/jonniek/mpv-playlistmanager/commit/e468aedd80ede2f7401534c94d232fe578435065 此提交的实现，明明只需要一个重置光标的功能就够了，他却保留了两个

**Comment by dyphire** [comment]
刚又发现此提交 https://github.com/jonniek/mpv-playlistmanager/commit/d2750f435e81632be14210b8bf3933d52bd9da87 破坏了原本的工作机制。个人修复 ：https://github.com/dyphire/mpv-playlistmanager

**Comment by hooke007** [comment]
这功能我也砍了（看的最近乱七八糟的commit心累
