### ISSUE TITLE
AMD 2500U 集显 Win10, SVP FIlter Script evalution failed

### ISSUE THREAD

**Issue by jiang-yuan** [hooke007/MPV_lazy#28]
![image](https://user-images.githubusercontent.com/36291537/136123186-c7cc31db-a31e-43f5-ba86-372900db6d00.png)
试了ctrl+3 ctrl+4 ctrl+5 都这样,开启 关闭SVP Filter GPU和CPU占用都没变化

**Comment by hooke007** [comment]
以ctrl组合键作为svp开关的版本是8月之前的了，用当前版测试一下

**Comment by hooke007** [comment]
我不了解svp的这个报错代码，可能是gpuid指定存在问题

**Comment by jiang-yuan** [comment]
> 我不了解svp的这个报错代码，可能是gpuid指定存在问题

官方说要更新显卡驱动,我更新到最新了还是没用
算了不弄也行,我明天用1660ti的笔记本不用这台了,应该就没问题了。

还有三个问题想请教下：
1.我看真人电影的话推荐用哪个补帧配置呢？
2. hwdec = nvdec-copy 是不是就能n卡自动硬解10bit了不用我再动什么了?
3. 目前缩略图有好的占用低的方案吗?感觉比Pot的卡好多,它的策略是不管我鼠标有没有移动到进度条都后台自己生成缩略图吗,还是我鼠标移上去才动态生成?

**Comment by hooke007** [comment]
HDR 视频涉及到tonemapping，这也是性能开销的大头。与解码效率关系不大（虽然默认使用的d3d11va-copy是比d3d11va要慢的

**Comment by hooke007** [comment]
4k+hdr+hevc10bit，就差一个源60fps就能把debuff叠满了。你过于低估svp的开销了

没有什么默认补帧，对应madvr的smoothmotion功能
https://github.com/hooke007/MPV_lazy/blob/4ba9e76e6750d88b27dcde4a10f9a9d3616223c2/portable_config/mpv.conf#L130-L134
