### ISSUE TITLE
Player does not remember the last played/opened video/file

### ISSUE THREAD

**Issue by FluffyDiscord** [hooke007/MPV_lazy#334]
Basically the title. I open up a video file, play it and also the next few in row (the automatic playlist it makes works nicely) then close the player. Next time opening it I expect it to remember at least the last file that was played, so I don't have to go one by one searching which episode I was yesterday. For some reason it always gets stuck at the last episode of some series and once I finish the next series, it gets stuck on that one, on the last episode.

**Comment by hooke007** [comment]
> the automatic playlist it makes works nicely

It needs to be clarified that what you saw is not playlist, it's sth like file-manager.

> Player does not remember the last played/opened video/file

mpv does don't have this feature natively, but there is some scripts could finish this job. I think you may need it. https://github.com/Eisa01/mpv-scripts#simplehistory

**Comment by FluffyDiscord** [comment]
Commit you mention does not seem to help, but the SimpleHistory you linked with `startup_idle_behavior=resume` does exactly what I want. Thank you
