### ISSUE TITLE
在非常用分辨率视频下雪碧图渲染出错

### ISSUE THREAD

**Issue by amlkiller** [hooke007/MPV_lazy#351]
![image](https://github.com/hooke007/MPV_lazy/assets/62412330/4fa2a092-b62f-4c2a-92f4-cdf881aa5af7)
效果如图
视频分辨率为1334*1920
复现：与正常视频打开一样
![image](https://github.com/hooke007/MPV_lazy/assets/62412330/ecef0220-5473-4345-90ae-732341cb727a)
样本由于原视频较敏感难以提供，我这里只要是分辨率不太常用都会触发（可能是ipad生成的视频的原因）

**Comment by hooke007** [comment]
附样本

**Comment by hooke007** [comment]
为什么需要样本，因为我的同分辨率一切正常。如果无法提高则视为视频自身的问题
