### ISSUE TITLE
当前版本osc_plus.lua无法正常显示，mpv控制台提示第2476行有错误

### ISSUE THREAD

**Issue by redomCL** [hooke007/MPV_lazy#378]
测试的mpv版本为 shinchiro/mpv-winbuild-cmake mpv-x86_64-v3-20231022-git-6e428c2.7z 

我在更新你的当前版本osc_plus.lua时发现无法正常显示，mpv控制台提示第2476行有错误

原2476行代码为 return return (minus..mp.get_property_osd(property .. "/full"))

改为 return (minus..mp.get_property_osd("playtime-remaining/full")) 错误消失，可以正常使用该osc

其实我不懂lua脚本，不过根据之前版本对照，这样更改后不报错了，osc_plus可以正常显示了，所以报告一下

刚才试了下 return (minus..mp.get_property_osd("property .. /full")) 也正常，不懂代码，你应该是双引号或者什么地方打错代码了？

**Comment by hooke007** [comment]
是多了一个 `return`
