### ISSUE TITLE
MPV: superxbr-chroma: from the log: Registering hook pass: unknown user shader

### ISSUE THREAD

**Issue by realdevnullius** [hooke007/MPV_lazy#392]
Is that warning / error to be expected? Or is something going wrong?

From my mpv.conf:
glsl-shaders="~~home/shaders/superxbr/superxbr-chroma.hook"

Same problems for superxbr-native.hook.

No other shaders are loaded. Thanks!

Which brings me to my bonus question... Is super-xbr--rgb--1.2-sharpness.hook used with 1 of the other 2 shaders (superxbr-native and super-xbr--rgb), or only with super-xbr--rgb?

**Comment by hooke007** [comment]
How to reproduce it?
https://github.com/bjin/mpv-prescalers/blob/1fb1c079405b674d54206ff2c52fd520db63ff10/superxbr-chroma.hook
It works fine here.

**Comment by realdevnullius** [comment]
Weird. Your link indeed has a !DESC which my file is missing. I downloaded the 3 shaders from https://github.com/hooke007/MPV_lazy/tree/bfea2cd24f34c0eb695eec44b25355db9bfb3d6d/portable_config/shaders because they appeared to be newer. I'll add the description tags and I think that'll solve it. Sorry. Thanks!

And if I may... What are the differences between all the super-xbr shaders you wrote? Any link I can catch up and try to understand when to use what?
