### ISSUE TITLE
AiUpscale shader not loaded? Log files show it loading, but when watching a video [ i 2] shows no loaded shaders, nor the !DESC given in the glsl file

### ISSUE THREAD

**Issue by realdevnullius** [hooke007/MPV_lazy#394]
mpv on Windows 11.

For example, I had an animated movie I wanted to watch so I loaded AiUpscale_HQ_4x_LineArt.glsl to test.

The logfile clearly shows it loaded succesfully.

But playing the movie nothing seems to be loaded / running / doing anything! The !DESC tag isn't shown either.

It's a 1080p movie on a 4k screen so plenty to upload I'd say? Am I missing something? Is there another test I can do?

**Comment by hooke007** [comment]
cannot help without log

**Comment by hooke007** [comment]
4x work only when your target size/source size ＞ 3.2x
You must misunderstand the logfile.

**Comment by realdevnullius** [comment]
AiUpscale_Fast_2x_LineArt.glsl works. This is the log for 

From the log:
 1.652][v][vo/gpu-next/libplacebo] Spent 40.272 ms loading cache
[   1.652][d][vo/gpu-next/libplacebo] Loaded 893 objects, totalling 31357106 bytes
[   1.652][d][vo/gpu-next/libplacebo] Spent 0.000 ms loading cache
[   1.652][d][global] user path: '~~home/shaders/AI_upscale/AiUpscale_HQ_4x_LineArt.glsl' -> 'C:\Users\Guido\AppData\Roaming/mpv/shaders/AI_upscale/AiUpscale_HQ_4x_LineArt.glsl'
[   1.660][v][vo/gpu-next/libplacebo] Registering hook pass: AiUpscale_HQ_4x_LineArt.glsl lanczos3

**Comment by realdevnullius** [comment]
> 4x would work only when your target size/source size ＞ 3.2x You must misunderstood the logfile.

I misunderstand the shaders mostly I suppose :) It's hard figuring it all out, but yes... Your answer makes sense... 1080 to 2160 is 2x max, not 3.2 or more... Is there a way to see in the glsl / shader files exactly how much upscaling will be done, is required? Because I've had this problem before :)

**Comment by hooke007** [comment]
nothing in log show the shader is loaded.
That's just the record of your action.

**Comment by hooke007** [comment]
Usually it is unnecessary for users to care about. It is designed by author. If it not work in such situation, this probably suggest that it is not the scenario for which it was designed to be used.

**Comment by hooke007** [comment]
BTW, many of 4x models are actually trained only for very low res sources (much worse than 720p). You really do not need to try this one...

**Comment by realdevnullius** [comment]
Appreciated!! Thanks for all your work :)
