### ISSUE TITLE
AiUpscale_Fast_2x_Photo.glsl # option 6 (increase gamma) increases dropped frames dramatically

### ISSUE THREAD

**Issue by realdevnullius** [hooke007/MPV_lazy#395]
Something else I noticed with an AiUpscale MPV shader... All was smooth and nice UNTIL I increased the gamma levels. Then, all frames starting dropping like flies. Is this a bug? :)

**Comment by hooke007** [comment]
> UNTIL I increased the gamma levels.

Cannot reproduce here.

**Comment by realdevnullius** [comment]
Problem is not with the shader but with MPV, sorry for hassling you. Even when no shaders are loaded, changing gamma levels starts dropping frames even when set back to the neutral (0) position. I moved my question to https://www.reddit.com/r/mpv/comments/18j429r/increasing_or_decreasing_gamma_levels_gives_lots/?utm_source=share&utm_medium=web2x&context=3

Peace! :)
