### ISSUE TITLE
请问如何让mpv记住上次的设置呢

### ISSUE THREAD

**Issue by rEco1LLLL** [hooke007/MPV_lazy#426]
- 如果你不确定是否应该提交 Issues ，那你大概率不需要，尽量提交到 [Discussions](https://github.com/hooke007/MPV_lazy/discussions)

- 不要报告mpv自身的问题。参考下方示例用命令行模式启动测试（整合包用户可以使用 installer 目录内的“纯净模式”），如果能复现那说明极大概率是mpv自身的问题而不是我整合的问题。
```
mpv --config=no --force-window=yes
```

- 关于整合包的报错，确保你已完整阅读过 [它的说明](https://github.com/hooke007/MPV_lazy/discussions/194)。别把“功能”当成 bug 提交。

- 良好的 Issue 应该尽可能满足如下要素：
标题简练并描述清楚问题；正文是详细的复现步骤、操作证明的截图、控制台信息或完整日志（更好）、特定文件产生的问题应附上切片样本...

**Comment by hooke007** [comment]
![20240312150711](https://github.com/hooke007/MPV_lazy/assets/41094733/982eb016-51df-4d97-9721-b14cffbfd2d6)
