### ISSUE TITLE
感觉字好像一直在闪，请问是显卡设置的问题吗？

### ISSUE THREAD

**Issue by hong-tm** [hooke007/MPV_lazy#5]
之前好像没有这个问题，最近升级了win 11 后发现这个问题，是不兼容吗？还是其他问题,谢谢大佬
![Snipaste_2021-07-03_02-54-23](https://user-images.githubusercontent.com/51999870/124318948-0cc49600-dbac-11eb-9fea-29b6af3f04c5.png)
![Snipaste_2021-07-03_03-05-46](https://user-images.githubusercontent.com/51999870/124318961-11894a00-dbac-11eb-900a-a8e8cd65be1e.png)
![Snipaste_2021-07-03_03-05-50](https://user-images.githubusercontent.com/51999870/124318981-177f2b00-dbac-11eb-9d12-d710835ceff3.png)

**Comment by hooke007** [comment]
...这是一个尚未正式发布的系统，整个工具链也没有任何针对win11的适配测试

**Comment by hong-tm** [comment]
欧，谢谢大佬回答，所以显卡设置应该没问题吧

hooke007 ***@***.***> 于 2021年7月3日周六 上午3:19写道：

**Comment by hooke007** [comment]
我对amd驱动设置不是很了解（a卡设备手边只有mbp）
之前win10测试并没有驱动里做任何修改一切正常
====
最近的一次编译版，本体替换成这个试试有无改善
[mpv_git_20210629.zip](https://github.com/hooke007/MPV_lazy/files/6756662/mpv_git_20210629.zip)

**Comment by hong-tm** [comment]
我替换了文件后就没有问题了，而且我也重装了驱动，现在没有看到会闪烁了，谢谢大佬帮助，我之前应该是下载了最新的版本吧。😎

hooke007 ***@***.***> 于2021年7月3日周六 上午3:38写道：

**Comment by hooke007** [comment]
...解决就行，大概率是驱动问题（
