### ISSUE TITLE
MPV设置音量时的显示

### ISSUE THREAD

**Issue by ccccxxx** [hooke007/MPV_lazy#8]
你好！
我使用MPV时，感觉设置音量时出现的提示与滑杆显示过大，影响观感。
实际使用时仅查看OSC进度条上的音量提示就足够了。

我尝试关闭OSC（使用Thumbnailer_OSC）显示后调节音量，依然会出现提示与滑杆。

请问有对应的设置可以关闭这项显示吗？或在哪个脚本里对其修改？

使用环境Win10 64位，使用脚本：
playlistmanager.lua
Thumbnailer.lua
Thumbnailer_OSC.lua
Thumbnailer_Worker.lua

**Comment by hooke007** [comment]
操作快捷键时的提示属于osd的一部分
input.conf 中相关指令前置 no-osd 即可，扩展阅读手册 05
`no-osd add volume 1`

另，osd的全体样式修改见mpv.conf的OSD部分

**Comment by ccccxxx** [comment]
> 操作快捷键时的提示属于osd的一部分
> input.conf 中相关指令前置 no-osd 即可，扩展阅读手册 05
> `no-osd add volume 1`
> 
> 另，osd的全体样式修改见mpv.conf的OSD部分
