### ISSUE TITLE
Thumbnailer_OSC结合7月的libass-git更新会显著增加windows下cpu占用

### ISSUE THREAD

**Issue by nyfair** [hooke007/MPV_lazy#9]
上个月libass git更新后改了font fallback的逻辑，会遍历整个font family。正常情况下渲染字幕这种一次性的流程并不会有太大影响，但是这个脚本渲染osd文字也走这个流程，而且每时每刻都在刷新

于是问题就来了，这个脚本的osc的定义里有这俩emoji
https://github.com/hooke007/MPV_lazy/blob/f62308f3e7561ab8da1719d572b5599dbbf21afc/scripts/Thumbnailer_OSC.lua#L160-L172
在非unicode的locale下（比如windows），通过luajit的转换，在lua_c api层面会添加0xfe0e这个emoji转义字符，这是个不可见字符，正常字体也不会有这种glyph，于是libass遍历完了所有字体还是找不到，cpu占用就这么上去了，我粗略测试下来把鼠标悬停在进度条预览缩略图时能吃满cpu半个核

实际上，这俩作用也就是在缩略图还没生成的时候借用libass生成一个简单的背景图然后贴个emoji上去，详见
https://github.com/hooke007/MPV_lazy/blob/f62308f3e7561ab8da1719d572b5599dbbf21afc/scripts/Thumbnailer_OSC.lua#L425-L440

把这些相关代码删了也不会造成太大影响

**Comment by hooke007** [comment]
感谢提醒。
测试下来425-440删除会影响脚本正常执行。最后采用了清空background和mini的赋值
